version: 2.0
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: |
            echo 'Bootstraping modules'
            npm i
            npm run bootstrap
      - run:
          name: Build
          command: |
            echo 'Build'
            npm run build
            npm run docs:build
      - run:
          name: Test
          command: |
            echo 'Tests'
            npm test
